# Generated by Django 5.2.6 on 2025-09-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tetx',
            new_name='text',
        ),
    ]
